### ISSUE TITLE
Add CollectionTrait

### ISSUE THREAD

**Issue by chrismichaels84** [chrismichaels84/data-manager#10]
A `CollectionTrait` extends `ManagesItemsTrait` and adds several helper methods:

There is no need to recreate the wheel, though. Import Stringy and some Array helper and user `Illuminate\Support\Collection` to fill in the rest of the holes

**Wish list**

- [ ] `flatten()` Get a flattened array of the items in the collection.

- [ ] `flip()` Flip the items in the collection.

- [ ] `diff(mixed $items)` Diff the collection with the given items.

- [ ] `each(callable $callback)` Execute a callback over each item.

- [ ] `filter(callable $callback = null)` Run a filter over each of the items.

- [ ] `groupBy(callable|string $groupBy, bool $preserveKeys = false)` Group an associative array by a field or using a callback.

- [ ] `keyBy(callable|string $keyBy)` Key an associative array by a field or using a callback.

- [ ] `implode(string $value, string $glue = null)` Concatenate values of a given key as a string.

- [ ] `intersect(mixed $items)` Intersect the collection with the given items.

- [ ] `keys()` Get the keys of the collection items.

- [ ] `last(callable $callback = null, mixed $default = null)` Get the last item from the collection.

- [ ] `pluck(string $value, string $key = null)` Get an array with the values of a given key.

- [ ] `map(callable $callback)` Run a map over each of the items.

- [ ] `max(string|null $key = null)` Get the max value of a given key.

- [ ] `merge(mixed $items)` Merge the collection with the given items.

- [ ] `min(string|null $key = null)` Get the min value of a given key.

- [ ] `pop()` Get and remove the last item from the collection.

- [ ] `prepend(mixed $value)` Push an item onto the beginning of the collection.

- [ ] `push(mixed $value)` Push an item onto the end of the collection.

- [ ] `pull(mixed $key, mixed $default = null)` Pulls an item from the collection.

- [ ] `reject(callable|mixed $callback)` Create a collection of all elements that do not pass a given truth test.

- [ ] `reverse()` Reverse items order.

- [ ] `search(mixed $value, bool $strict = false)` Search the collection for a given value and return the corresponding key if successful.

- [ ] `shift()` Get and remove the first item from the collection.

- [ ] `shuffle()` Shuffle the items in the collection.

- [ ] `slice(int $offset, int $length = null, bool $preserveKeys = false)` Slice the underlying collection array.

- [ ] `sort(callable $callback = null)` Sort through each item with a callback.

- [ ] `sum(callable|string|null $callback = null)` Get the sum of the given values.

- [ ] `transform(callable $callback)` Transform each item in the collection using a callback.

- [ ] `unique(string|callable|null $key = null)` Return only unique items from the collection array.

- [ ] `count()` Count the number of items in the collection.

**Comment by PommeVerte** [comment]
See my comment in the PR about this. 
It's not to say that having the trait isn't a good thing. It should however be used sparingly. A few of these methods would be better used doing different tasks in classes that would extend `Collection`

**Comment by chrismichaels84** [comment]
This will be split into two milestones. Basic for v0.8.6 and full for v0.9

**Comment by chrismichaels84** [comment]
Decided to use Arrayzy, with their api
