### ISSUE TITLE
Hydrate from various non-native data types

### ISSUE THREAD

**Issue by chrismichaels84** [chrismichaels84/data-manager#29]
Now that `hydrateFrom()` has landed, the next step is to add a system for users to register `Decoders` that allow for hydrating and appending from any kind of non-native datatype.

This would also mean a `JsonDecoder` and probably a `YamlDecoder` standard

**Comment by smolinari** [comment]
Can you explain a bit more what you mean by the user's ability to register a decoder? What would be a simple example and the expected steps taken to do the registering?

Scott

**Comment by chrismichaels84** [comment]
So, this is what I was thinking:
```php
$manager->hydrateFrom('json', $data'); // Works as it is
$manager->hydrateFrom(new XmlDecoder(), $data); // Uses supplied decoder to hydrate
```
So, if the user passes a string, it is checked against the built-in types (probably just json and yaml), but if they pass an object, it is checked against the interface `DecoderInterface` which offers a `prepare($data)` method and a `decode($data)` method. The implementation simply returns a php-array that can be hydrated or appended.

Btw, after I ran the code through scrutinizer, it showed me some code duplication in the new `hydrateFrom()` and `appendFrom()` methods, so I extracted all the validation and type checking to its own protected method that both of the above use. Take a look to see what I mean.

**Comment by smolinari** [comment]
Ok. Got it. 

Scott

**Comment by smolinari** [comment]
I'd like to take this on, but make some changes to the way things work currently. 

1. The method `hydrateFrom()` will be the only method to "hydrate" with. No `appendFrom()`. Appending should be  an option to the hydration.
2. So, the method signature will look like this.
`public function hydrateFrom(TypeInterface $typeInterface, $data, $append = 'false');`.
3. I build the yamlDecoder and jsonDecoder decoders and put them in a `/decoders` directory along with the interface.

On one change you made, changing the private methods to protected, why was this wanted or necessary? I'd like to understand, from a noob dev perspective. Doesn't that change make the interface to the manager less concise or watered down? I went looking for answers on the do's and don'ts of private and protected and came up with this article from Fabien Potencier, which I tend to agree with, although I don't have the experience to back up that agreement either. So, this is me, a learning dev trying to understand the motivation. 

http://fabien.potencier.org/pragmatism-over-theory-protected-vs-private.html

Scott

**Comment by chrismichaels84** [comment]
It's not at all required, and there is a memory upside to using private and public over protected. The reason I prefer protected over private for something like this is because `Manager` should be extendable in every way, and if you extend a class, the private methods are not inherited. So, for libraries that are meant to be mixed into other libraries/applications, I like protected. For applications or modules I use private whenever I can because I know that if I need to extend it, I can change that pretty easily without throwing anyone else off.

I guess its more personal preference than anything, and I'm not about to go up against someone like fabien.

The changes to hydrate sound great. Thanks!

**Comment by smolinari** [comment]
Thanks. I just wanted to be sure I wasn't doing something basically wrong. :+1: 

Scott

**Comment by smolinari** [comment]
I added an unfinished pull request, and discussed the interface usage in the `hydrateFrom()` shortly with another dev acquaintance of mine. He noted, why not just return the array data out of the decoders "upstream" of the data-manager? That way, we can use the `reset()` and `add()` methods directly. I guess my question is, do we really need to have a `hydrate()` method to begin with? I mean, theoretically, we could, for instance, just use Symfony's YAML component to deliver array's out of yaml and feed them into `reset()` or `add()`, couldn't we?

Scott

**Comment by chrismichaels84** [comment]
We could, and I like dropping `hydrate`, but the reason I wanted decoders was for loading external files. I want there to be an easy way to simply `loadFromFile()` and Manager to detect the format (based on file type) and pipe it through the correct decoder. This is more an intermediate step for that.

We could merge hydrate and append *into* reset and add. Simply add another argument for an optional decoder?

**Comment by chrismichaels84** [comment]
To clarify what I mean by loading files, see the new comment on #25.

That said, I think I'd like to keep `hydrate` separate from `reset` for now. We can revisit this before 1.0 when the api becomes stable.

**Comment by smolinari** [comment]
So, the `load()` method needs to be a smart method for loading different config files. How about we just integrate Symfony's own config component?

https://github.com/symfony/Config
http://symfony.com/doc/current/components/config/resources.html

>Config provides the infrastructure for loading configurations from different data sources and optionally monitoring these data sources for changes. There are additional tools for validating, normalizing and handling of defaults that can optionally be used to convert from different formats to arrays.

>For each type of resource (YAML, XML, annotation, etc.) a loader must be defined. Each loader should implement LoaderInterface or extend the abstract FileLoader class, which allows for recursively importing other resources:

Sounds a lot like the wheel you want to fit onto the data manager cart.

:smile: 

Scott

**Comment by chrismichaels84** [comment]
I agree they are solving a lot of the same problems, but Manager shouldn't have any other dependencies. Suggested is fine (life Finder or Decoders), but not hard dependencies.

The purposes of Manager (and what hopefully makes it distinct) are lightweight, composable, and simple. Symfony components are great, but are very complex and reliant on each other, and not composable.

Does that make sense?

Truthfully, the loading files is not much of a trick. The SPL will get a filetype without any dependencies.

Btw, I am a writer by trade, and I want to compliment your wordchoice "wheel you want to fit onto the Manager cart"

**Comment by chrismichaels84** [comment]
The method responsibilities (from my pov) would be:
   * `load($file|$files, $append);`: locates file, confirms existence, pulls mime type, loads file and passes to
   *  `hydrate($data, $decoder, $append)`: accepts native data, pipes it through correct decoder, and appends or resets the data to manager
   * and, of course, protected methods that split that work up into nicely testable units :smile:

**Comment by chrismichaels84** [comment]
All of the above (including YAML and JsonDecoders) are possible with the SPL and no external dependencies. I am a huge fan of Symfony components and use them in every project. It's just not the direction I want to take Manager specifically.

**Comment by smolinari** [comment]
> Does that make sense?

Sort of. I did see the file component, which the config component requires, is a bit of overkill for just a file importer.  

Ok. I'll see what I can do. 

I can't find any reasoning,  but if SPL has a yaml_parse function, why would anyone need Symfony's yaml component? 

Scott

**Comment by chrismichaels84** [comment]
The symfony yaml package offers some advantages over native `yaml_parse()`, mostly loading and parsing files in one shot. It's also a nice abstraction that makes the api familiar across all of symfony. Symfony also provides better error messages.

And, I just realized, this function is not available in standard php distributions. That could be a problem :( 

We may *have* to use symfony's yaml parser to decode and then `suggest` it in the composer file. That way, the user can install symfony yaml if they are using the yaml decoder?

**Comment by smolinari** [comment]
This is like a really noob kind of question, but I found a small project, which is pretty close to what we need for the `load()` feature. However, you said, you didn't want dependencies. 

https://github.com/caseyamcl/Configula

To avoid the dependency, I'd need to do a bit of "copy and paste" of the source code from that project. ( and doing that would be 1000x faster than me coding it all on my own, to be honest). What is the rule on that kind of ehem....."borrowing"? Could we just make a reference that the config file loading feature was based on that project in the docs to give credit? Or should we actually use the library, and go against the dependencies rule you've set? I am sort of for the former, as I do want to learn a little from this exercise.   

It is MIT licensed. What to do?

Scott

**Comment by chrismichaels84** [comment]
Yeah, you can definitely use pieces of this to get started. Just remember that the configuration loading uses the ManagesItemsTrait methods, so be sure to use `get()`, `set()` etc when appropriate.

As far as credit, I really like to give credit where credit is due. For this, I give credit in the source code when something is borrowed, make a note in the CHANGELOG, and give a shoutout in the README under credits or special thanks.

In the source code:
```php
/* Cycle through whatever */
foreach ($whatever as $whatever) {
    /* Do something cool */
    // Originally from https://github.com/caseyamcl/Configula/blob/master/src/Configula/Config.php
    // Configula by @caseyamcl, MIT Licence
    if (whatever === whatever) {
        return whatever;
    }
}
```

Include that comment wherever the code is borrowed.

**Comment by smolinari** [comment]
> Just remember that the configuration loading uses the ManagesItemsTrait methods, so be sure to use get(), set() etc when appropriate.

What happened to:

>The method responsibilities (from my pov) would be:

>`load($file|$files, $append, $optionalDecoder);`: locates file, pulls mime type, loads file, and decides which decoder to use if not decoder is supplied, then passes to
`hydrateFrom($decoder, $data, $append)`: accepts native data, pipes it through correct decoder, and appends or resets the data to manager
and, of course, protected methods that split that work up into nicely testable units :smile:

Scott

**Comment by chrismichaels84** [comment]
That's all the same. All I'm saying is that the files are decoded and then loaded into the existing `items` array using the existing methods `reset()`, `get()`, `set()`, etc. Just like `hydrateFrom()` currently does. 

The workflow you quoted is what I was describing because `hydrateFrom()` uses `reset()` or `set()`.

Does that make sense?

**Comment by smolinari** [comment]
So, I need to offer the ability to read a different config files (`load()`method), get the file data into an array through a driver/ decoder and add that data to the manager. Or if wanted, do a reset of the manager with that data. At the same time, I need to offer a means to add a custom driver/ decoder to load the data too. 

Correct?

Scott

**Comment by chrismichaels84** [comment]
Yep, that sounds about right. I would think offering a custom driver/decoder may be best as an optional argument.

I do appreciate your help. You are going to tackle this, then? If so, I'm going to begin work on adding optional collections support :)

**Comment by chrismichaels84** [comment]
And I was wrong earlier. We do need to use symfony/yaml for yaml decoding. The native yaml parser is not installed by default. That's my bad. That is one situation where we can "suggest" a dependency through composer, so if they want to use yaml, they can simply require symfony/yaml. Json can be native. I don't know that we need any other formats by default, do you?

**Comment by smolinari** [comment]
Yes, I'm working on this. I've added the Symfony YAML library. The only other driver I'd suggest is a plain PHP one. 

Scott

**Comment by chrismichaels84** [comment]
cool. The plain php one could just `$data = include $file` and `$file` could `return []`. That's standard convention as far as I've seen.

**Comment by smolinari** [comment]
I am sort of stuck on a few things. 

You mentioned in the API examples that `load()` could take a file or list of files. However, I am certain the files to read won't be stored within the data manager directory. So, a basic piece of data that needs to be with each file is the file's actual location. This works well with the Symfony finder example you had posted in #25, since the return data from finder has the file locations in the data too.

I guess my question is, should there also be the file location with the file data? Could we we require one SplFileInfo Object or an Iterator of SplFileInfo Objects, like Symfony's finder returns? 

Is the load method supposed to be used multiple times by the user for different config file types using custom decoders? Not sure why that would be necessary, but if there are different decoders and they are needed at different times, then the user will have to call on them separately and each time they want to use it. 

In general, and this might be totally screwed up thinking, instead of calling a load method in the manager, which sort of breaks SRP (doesn't it?), the decoder functionality should be in its own "Loader" module and should get the manager injected. So, we would have on the client side. 
```
$loader = new Loader(Manager $manager);
$loader->load($file|$files, $append);
//we can also have
$loader->addDecoder(DecoderInterface $newDecoder);

```  
That way, the custom decoder is added once, but can be used anytime and as often as needed later. (Obviously, the addDecoder call would need to be before any call to load files too.)

With a Loader class/ module, we also don't necessarily need the `hydrateFrom()` method either, keeping the manager simple and clean. Though, if you want to keep it as an added feature, why not? I guess.

Am I in left field now? :blush: 

Scott

**Comment by chrismichaels84** [comment]
You definitely aren't in left field, and those are good points I hadn't considered. I think I see two questions there:

> I guess my question is, should there also be the file location with the file data? Could we we require one SplFileInfo Object or an Iterator of SplFileInfo Objects, like Symfony's finder returns?

I was thinking that we would just require the absolute path at the time the `load()` method was called: `$manager->load(__DIR__ . '/../../config/file.json');`. From there, its easy for Manager to load the file, because it already knows the exact location. That said, it may be clunky if loading a lot of files. I think you are right that requiring the native php SplFileInfo would be a good way to go (at least for now). That way they can inject `$finder` or anything else that produces a file info.

> instead of calling a load method in the manager, which sort of breaks SRP (doesn't it?), the decoder functionality could be in its own "Loader" module and would get the manager injected.

This is another good point and I was just thinking about this yesterday. `Manager` is getting more bloated than I had originally wanted, though I don't know that I like injecting Manager *into* a loader because in many cases, loading the files will only be one way of setting configuration data.

So, the way I see it, we have two options for cleaning up the SRP problem:

  1. **Use a LoadsConfigItemsTrait**: This is kind of the convention that the rest of the package uses. `ManagesItemsTrait` holds the most basic functionality and the other traits can be mixed and matched to get the desired extra functionality (using magic methods, collections, dependency injection, etc).

  2. Add a `Loader` or `FileBag` class to handle registering decoders, files, and the like. This class would be responsible for loading the file, decoding to an array, and returning the resulting array to `Manager` to be set or appended.

I'd like your opinion, but the best thing may be to do both, or really all three. This is what I mean:

   * Remove all hydrate and loading from `ManagesItemsTrait`
   * Create a new trait `LoadsConfigFilesTrait` that `use`s `DependsOnManagesItemsTrait` (which only ensures that the user doesn't use a sub trait without the primary one)
   * `LoadsConfigFilesTrait::hydrateFrom();` probably stays the same as it is now. No file loading.
   * `LoadsConfigFilesTrait::load($splFileInfo, $decoder);` for a **single** file only.
   * `LoadsConfigFilesTrait::load(FileBag $bag);` for **multiple** files and cascading files (worry about those later).
   * The `FileBag` holds each file to be loaded with the accompanying decoder. You can also register decoders and use an alias.
```php
// We have three options for loading files, depending on use case, and of course, mix and matched
// Add each file with a specific decoder
$bag = new FileBag();
$bag->addFile($splFileInfo, $decoderObject);
$bag->addFiles([
    [$splFileInfo, $decoderObject],
    [$splFileInfo, $decoderObject],
]);

// OR, register a decoder to be used
$bag->addDecoder('xml', new XMLDecoder());
$bag->addFile($splFileInfo, 'xml');

// OR, maybe add a default decoder
$bag->setDefaultDecoder(new XmlDecoder());
$bag->addFile($splFileInfo);
$bag->addFiles([$splFileInfo, $splFileInfo, $splFileInfo]);
```
   * The `FileBag` ONLY holds files objects with their decoders, it does not load files.
   * So, when `LoadsConfigFiles::load($bag|$splFileInfo);` is called, the `load` method spins up a new `FileLoader` class which accepts a `$splFileInfo` or `$bag`, finds and loads files, decodes them, and returns the finished array, which `LoadsConfigFiles` appends or resets as appropriate.

Does that make sense? Does that address your questions? Do you have any different ideas? If you still want to inject `Manager` into a `Loader`, could you show me an example of what you mean so I can understand better?

**Comment by chrismichaels84** [comment]
This has got me thinking about SRP, and I appreciate that. Let's lay out exactly what each responsibility would be:

   * The `ManagesItemsTrait` CRUDs against a deeply nested data array.

All the other Traits add extensions or sugar to this basic responsibility, either in the way the data is accessed or in the kind of data.
   
   * `ManagesIocTrait` CRUDS object factories against a data array
   * `ChainsNestedItemsTrait` allows for CRUD access via magic methods
   * `ArrayableTrait` allows for CRUD access via array syntax
   * `LoadsConfigFilesTrait` will provide api to load files into the deeply nested data array

The Other Classes:
   * `FileLoader` loads files, decodes using dependency, and returns final array
   * `FileBag` is a DTO that keeps each file with desired decoder
   * `xyzDecoder` decodes data to php array. does not load files.

The Manager classes are simply concrete classes that use various combinations of traits for ease of use.

I have planned to rework the documentation as we near 1.0. This belongs there.

Any thoughts?

**Comment by chrismichaels84** [comment]
I like where this is headed. Thanks for your help.

**Comment by smolinari** [comment]
Sounds good. 

The only thing that I wanted to try and do a bit differently was to have the extension be the convention to call the decoder, like how Configula does it. 
```
        $decoderClassname = 'Michaels\\Decoders\\'.ucfirst(strtolower(pathinfo($filepath, PATHINFO_EXTENSION)));
        if (class_exists($decoderClassname)) {
            $decoder = new $decoderClassname();
            $decoder->read($filepath);
            return $decoder->decode();
        } else {
            return array();
        }

```

So, if someone wants to write their own decoder, they can, but the convention would be the class must be named after the file's extension. Like `myConfig.xml`. The decoder class name would have to be "Xml" and also extend an abstract decoder class. Though, to be a bit different, we can add "Decoder" to the class names. So, the class name would be `XmlDecoder`.

`'Michaels\\Decoders\\'.ucfirst(strtolower(pathinfo($filepath, PATHINFO_EXTENSION))).'Decoder';`

Scott

**Comment by chrismichaels84** [comment]
The problem with that is, what about third-party decoders? They may not be able (and shouldn't) place decoders in the Manager composer directory. That should be isolated from their system. The custom decoders should be under whatever namespace is appropriate.

**Comment by chrismichaels84** [comment]
So, I've been thinking that I like the idea of being able to register a Decoder and letting the file loader choose the decoder based on MIME type. I still don't think the configuration/namespace option is the right way to go, but what if the Decoder itself can describe which MIME type it handles?

```php
class XmlDecoder implements DecoderInterface {
    public function mimeType() {
        return 'xml'; // or whatever the SplFileObject spits out when asked for extension
    }

    public function decode($data) {
        return [];
    }
}

$loader->addDecoder(new XmlDecoder());
```

The `addDecoder()` method asks the decoder for its desired MIME type and associates them. That way, when the user `$loader->load($splFile);` it checks the extension of the file and uses the registered decoder for that filetype.

In this case, we would actually create a Json and Yaml decoder and just register them automatically within the loader. The user can then add as many decoders as they like.

What do you think?

**Comment by smolinari** [comment]
Ah, yes. For that we would have the `addDecoder()` method in the `FileLoader`. The client coder will only call it once to install her decoder and off she goes. 

Scott

**Comment by smolinari** [comment]
Ok. I started over actually and made a push to my repo with a starting bit of code for the FileBag and also added just the files (empty). Can you check it out and tell me if that is the right direction, but more from a "where things need to go" perspective?

https://github.com/SkooppaOS/data-manager

Scott

**Comment by chrismichaels84** [comment]
Yeah, everything looks in the right place to me. Good naming and namespacing. The `hydrateFrom()` method itself probably belongs in `LoadsFileTrait`, but the actual logic of that exists now would belong in the decoder, so I assume you'll split that up as time goes on. Good tests.

Eventually `DecoderInterface` will need some sort of `mimeType()` or `handlesFileType()` method so it can declare which type it handles. Types?

Also, before you issue a PR, can you remove your .idea folder from git tracking. 

See
http://git-scm.com/docs/git-rm
http://stackoverflow.com/questions/1273108/how-do-i-git-rm-a-file-without-deleting-it-from-disk

**Comment by smolinari** [comment]
Ok. Yeah, I'll git rid of the .idea folder. <-see what I did there? LOL! :smiley: 

Scott

**Comment by chrismichaels84** [comment]
lmao!

**Comment by smolinari** [comment]
Ok. I did some more work and I actually did it without following Configula. I feel that is good, because I have learned more. It is probably disadvantageous, because I am probably making more noob mistakes. :smile: 

At any rate, I now have a working FileBag, JsonDecoder and FileLoader and it actually all works (current tests pass). And either files (as an array of SplInfoObjects) or a FileBag can be passed to the `FileLoader`. 

I know I am  not completely going in the direction you intended, so let me know what is wrong or what you'd like to see different. It is all my feeble experience and knowledge could let me create. 

As you can see, there are also still some tests to complete. If you have further suggestions on testing, let me know. And I need to move the `addFiles()` method to the `LoadsFilesTrait` trait (need to change the name). But, to be honest, I am not sure why this is needed. LOL! :smile: There is no code reuse necessary at the moment, is there???

Scott

**Comment by smolinari** [comment]
Ok. Check out what I did. We now have the API additions.

$manager->loadFiles($files, $append)

$manager->addDecoder(\DecoderInterface $decoder)

Things to do still (so I don't forget. :smile:)

 - [ ] Create the YAML decoder with tests
 - [ ] Create the PHP decoder with tests
 - [ ] Create some custom decoder and test its addition and decoding properly (suggestions on what kind are welcome).
 - [ ] Do tests for appending with file data

Any other tests?

Scott

**Comment by chrismichaels84** [comment]
Would you mind copying this to the PR. I like to keep these kinds of things along side code so we can comment back and forth more directly :) I'll take a look at all this tonight. I would just create a StubDecoder that implements the interface and returns some standard array. It doesn't have to be functional to test if its been registered and such.

**Comment by smolinari** [comment]
You lost me on this:

> I would just create a StubDecoder that implements the interface and returns some standard array. It doesn't have to be functional to test if its been registered and such.

So, I am going to plug along on the todos. 

Scott

**Comment by PommeVerte** [comment]
@smolinari The reference to Stub means that it's a "fake" class of sorts that reproduces the behavior of `Decoder` in a predictable way. Often to inject that class into whatever other class/method you are testing. That way since you know the stub will always return predictable output if a failure occurs it's necessarily linked to the other class. 
You can do this either by creating a new class file somewhere in tests, or in some cases by using phpunit's stub/mock features to modify existing classes.

I haven't followed these devs so I really don't know what the context is here but hopefully that nudges you in the right direction.

**Comment by smolinari** [comment]
@PommeVerte - Thanks. So Chris was meaning that I should create fake decoders, since the decoders were tested as units already. Though, it seemed easier to me to use them directly than to try and fake them. That might be due to my lack of experience though. I'll see if I can learn to stub and do it. 

Scott

**Comment by PommeVerte** [comment]
Yes. The difference between the two approaches you suggest is that when using a stub if someone refractors the real decoder and breaks it then only the decoder tests break and not the ones that depend on decoders. This allows for better compartmentalizations of your tests and easier tracking of errors

**Comment by smolinari** [comment]
Ah, yes. That is something I was thinking about, when I wrote the tests. The "what all will break, when a decoder is broken" scenario. Ok. Understood. And, it also helps put the right frame (of mind) around what I need to do to. Thanks.

Scott

**Comment by PommeVerte** [comment]
No problem! And just to elaborate a bit (though you seem to know this already):

Ideally if you brake one method of one class, you should only ever have one unit test that fails (sometimes easier said that done)

Using the actual decoders with other parts of the code to make sure they integrate properly would fall out of the unit testing realm into the integration testing :)

Cheers,
Dylan.

**Comment by smolinari** [comment]
Yeah, to be honest, this is the first ever unit test writing I've ever done (along with any serious PHP programming too). So, most certainly learning by doing. I appreciate the mentorship you gents are giving me. I need it. LOL! I sure wish I had learned to do more programming earlier in my life. I'd be a lot further with my project, than I am now. But, that is ok. It is all just a hobby, currently. No stress.  

Scott

**Comment by chrismichaels84** [comment]
Merged
