### ISSUE TITLE
Namespacing data loaded from files

### ISSUE THREAD

**Issue by chrismichaels84** [chrismichaels84/data-manager#36]
There is a potential flaw in the way the `FileLoader` constructs its array data atm. If two files are loaded and share some key, whichever is loaded last overwrites the first. There should be a way around this, and it should probably not do this by default.

To be clear, this is not the same as #34.

This is what I mean.
**hello.json**
```json
{
  "one": 1
}
```

**world.php**
```php
return [
  'one' => 'one'
]
```

In this case, world.php *overwrites* hello.json.

## Possible Fixes
There are a couple options to correct this.
   1 Auto namespace items based on (sanitized) filename

**hello.json**
```json
{
  "one": 1
}
```

**world.php**
```php
return [
  'one' => 'one'
]
```

```php
$manager->getAll();
/*
[
   'hello' => [
      'one' => 1
   ],
   'world' => [
      'one' => 'one'
   ]
]
*/
```
   2 Give the user the ability to decide a namespace

```php
$manager->addFiles([
   [SplFileInfo, 'someCustomNamespace'],
   [SplFileInfo, 'someOtherNamespace'],
]);
```
Which would namespace each file under that particular namespace.

   3 A combination of both would probably be best

**hello.json**
```json
{
  "one": 1
}
```

**world.php**
```php
return [
  'one' => 'one'
]
```

```php
$manager->addFiles([
   [SplFileInfo('hello.json'), 'myNs'],
   SplFileInfo('world.php'),
]);


$manager->getAll();
/*
[
   'myNs' => [
      'one' => 1
   ],
   'world' => [
      'one' => 'one'
   ]
]
*/
```

## Things to be aware of
  * Filenames can have really bad practices, and so should be sanitized/slugified. We can borrow from Stringy.
  * If two files have the same filename, the problem doesn't correct itself. That's fine with me. The user should know what they are loading and be aware of how it works. If we provide them an namespace option, they should use it.
  * The override namespace api for this is incompatible with the proposed api for #34

## From here
I'd like to do some research into Laravel, Symfony, and Yii. I know they all do this and have used all three, but never noticed how they handle this little issue. Any other thoughts are welcome.

**Comment by chrismichaels84** [comment]
Added to `develop` branch

**Comment by smolinari** [comment]
I am not sure how I missed this issue. But I did. Does something still need to be done? Sort of confused by the "Added to develop branch" comment. 

Scott

**Comment by chrismichaels84** [comment]
No it was super simple. Only took me a few minutes. Thanks though :)
